baseurl = "https://frankly-no.github.io/BadRep/"
languageCode = "en-us"
title = "BadRep(a record label)"

[params]
logo = "img/logo.png"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 3

[[menu.main]]
name = "Artists"
url = "/artists/"
weight = 4

